spring.application.name=steam-accountibilibuddy
server.port=8080

# Base URL of this app (must match return_to realm when testing)
app.base-url=http://localhost:8080

# Steam endpoints / API key
steam.openid.endpoint=https://steamcommunity.com/openid/login
steam.api.key=${STEAM_API_KEY:}
steam.api.base=https://api.steampowered.com
#steam.wishlist.url=https://api.steampowered.com/IWishlistService/GetWishlist/v1/

logging.level.root=INFO
logging.level.com.yourorg=DEBUG